Kaarina Mattika, CS87A, Section 1758
https://github.com/kmattika/cs82a-portfolio

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [2]:
df = pd.read_csv(r'C:\Users\kamat\Downloads\ratings.tsv', sep='\t')
display(df.head(10))
display(df.shape)
display(df.info())
display(df.describe())

   restaurant  food  ambience  service  rating
0           1    85        82       89      78
1           2    80        90       80      85
2           3    83        86       83      85
3           4    70        96       75      72
4           5    68        80       78      75
5           6    65        70       56      54
6           7    64        68       61      62
7           8    72        95       72      73
8           9    69        70       78      70
9          10    75        80       75      77

(15, 5)

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   restaurant  15 non-null     int64
 1   food        15 non-null     int64
 2   ambience    15 non-null     int64
 3   service     15 non-null     int64
 4   rating      15 non-null     int64
dtypes: int64(5)
memory usage: 732.0 bytes

None

       restaurant       food   ambience    service     rating
count   15.000000  15.000000  15.000000  15.000000  15.000000
mean     8.000000  73.133333  81.733333  75.133333  73.066667
std      4.472136   6.555986   9.786774   8.069932   8.319226
min      1.000000  64.000000  68.000000  56.000000  54.000000
25%      4.500000  68.500000  71.000000  73.500000  70.500000
50%      8.000000  72.000000  82.000000  78.000000  74.000000
75%     11.500000  77.500000  90.000000  78.000000  77.500000
max     15.000000  85.000000  96.000000  89.000000  85.000000

In [3]:
X = df[['food', 'ambience', 'service']]
y = df['rating']
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42)

print('X_train:', X_train.shape)
print('X_test:', X_test.shape)
print('y_train:', y_train.shape)
print('y_test:', y_test.shape)

X_train: (10, 3)
X_test: (5, 3)
y_train: (10,)
y_test: (5,)

In [4]:
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print('Coefficients:', model.coef_)
print('Intercept:', model.intercept_)
print('R-squared:', model.score(X, y))

Coefficients: [0.95676835 0.07401426 0.20380826]
Intercept: -17.214438121026205
R-squared: 0.7568095296184247

In [5]:
predictions = pd.DataFrame({
    'Actual Rating': y_test,
    'Predicted Rating': y_pred
})

display(predictions.round(3))

    Actual Rating  Predicted Rating
9              77            75.750
11             76            74.231
0              78            88.319
13             71            71.922
5              54            61.570

In [6]:
coefficient = pd.DataFrame({
    'Factor': X.columns,
    'Coefficient': model.coef_
})

coefficient = coefficient.sort_values(
    by='Coefficient',
    ascending=False
)

display(coefficient.round(3))

     Factor  Coefficient
0      food        0.957
2   service        0.204
1  ambience        0.074

From the analysis present, food is the overwhelming factor that influences ratings for a restaurant in our model. This seems to reflect a real-world shift of the business case in the food industry - consumers are consuming prepared food in more modalities than a decade ago, with food delivery apps and food trucks capturing more market engagement during and after the covid-19 pandemic. Thus, we can theorize that service (which can be outsourced to third party delivery apps, or be as simple as waiting for food to be served at a kiosk to-go) and ambience (which is cut out entirely with food delivery and to-go dining options) are overwhelmingly inferior factors to the quality of the food itself.