Kaarina Mattika, CS87A, Section 1758
https://github.com/kmattika/cs82a-portfolio

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv(r'C:\Users\kamat\OneDrive\Desktop\CS82A\allbacks.csv')
display(df.head(10))
display(df.shape)
display(df.info())
display(df.describe())

   rownames  volume  area  weight cover
0         1     885   382     800    hb
1         2    1016   468     950    hb
2         3    1125   387    1050    hb
3         4     239   371     350    hb
4         5     701   371     750    hb
5         6     641   367     600    hb
6         7    1228   396    1075    hb
7         8     412     0     250    pb
8         9     953     0     700    pb
9        10     929     0     650    pb

(15, 5)

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   rownames  15 non-null     int64
 1   volume    15 non-null     int64
 2   area      15 non-null     int64
 3   weight    15 non-null     int64
 4   cover     15 non-null     str
dtypes: int64(4), str(1)
memory usage: 762.0 bytes

None

        rownames       volume        area       weight
count  15.000000    15.000000   15.000000    15.000000
mean    8.000000   845.266667  182.800000   706.666667
std     4.472136   339.879909  203.586837   268.837887
min     1.000000   239.000000    0.000000   250.000000
25%     4.500000   618.000000    0.000000   512.500000
50%     8.000000   929.000000    0.000000   725.000000
75%    11.500000  1025.000000  376.500000   950.000000
max    15.000000  1492.000000  468.000000  1075.000000

In [11]:
df['cover'].sort_values().iloc[len(df)//2]

'pb'

I found part of this solution when researching on stackoverflow how to find the median entry for a list of string Dtype values. I had the idea of sorting the values and using 'iloc' to find the middle value of that list by myself, but struggled with discovering the proper syntax to write the query. The link to the stackoverflow article is here: https://stackoverflow.com/questions/76974463/median-of-string-values-in-a-pandas-series-or-groupby-object-using-built-in-me

In [12]:
print("The mean weight of all books is", df['weight'].mean())

The mean weight of all books is 706.6666666666666

In [14]:
print(df.groupby('cover')['weight'].mean())
print(df.groupby('cover')['weight'].median())

cover
hb    796.428571
pb    628.125000
Name: weight, dtype: float64
cover
hb    800.0
pb    675.0
Name: weight, dtype: float64

The higher mean value for the hardcovers compared to the paperbacks suggests that the material and construction norms used in hardcovers is of greater weight than those used in paperbacks. Heuristically, this is true, and it is also supported by the data - hardcovers are more than 150 units heavier when calculated by the mean. Using the median as a comparison, there is a pretty close grouping to the mean as well; the lack of extreme minimum or maximum values outside of two standard deviations also supports the use of the mean as a good yardstick of analysis here. In discovering the median value for cover types, I checked by hand if manually sorting via a bidirectional algorithm, where I grouped the values together and removed the max and min values simultaneously. I performed this with the column's string values sorted from A-Z and Z-A, and received the same answer each time.