Kaarina Mattika, CS87A, Section 1758

Step One Problem

In [1]:
name = "Laney"
hourly_wage = 25.5
hours = 40
weekly_wage = hourly_wage * hours
print(f"{weekly_wage} is Laney's weekly pay.")

1020.0 is Laney's weekly pay.

Step Two Problem

In [2]:
temps = [61, 65, 72, 58, 70, 74, 68]
high = 0
for s in temps:
    if s > 65:
        high = high + 1
print(high)

4

Step Three Problem

In [3]:
def to_celsius(f):
    return (f - 32) * 5/9

print(round(to_celsius(temps[0]), 1))

16.1

Step Four Problem

In [4]:
movie = {"Title": "Garden State", "Year": 2004, "Rating": 100}
for key, value in movie.items():
    print(key, ":", value)

Title : Garden State
Year : 2004
Rating : 100

Step Five Problem

In [6]:
import pandas as pd
df = pd.read_csv("C:/Users/kamat/Downloads/chickwts.csv")
display(df.head())
display(df.shape)
display(df.describe())

   Unnamed: 0  weight       feed
0           1     179  horsebean
1           2     160  horsebean
2           3     136  horsebean
3           4     227  horsebean
4           5     217  horsebean

(71, 3)

       Unnamed: 0      weight
count   71.000000   71.000000
mean    36.000000  261.309859
std     20.639767   78.073700
min      1.000000  108.000000
25%     18.500000  204.500000
50%     36.000000  258.000000
75%     53.500000  323.500000
max     71.000000  423.000000

Step Six Problem

I was surprised that the head knew to include the title values on it's own, and not as a data row. From the data itself, however - a large standard deviation highlights how critical this problem is in a real-life scenario for a business attempting to generate revenue and confident business projections. The high standard deviation in this data is something to be avoided, and while the 'df.describe()' functio